version: '3.8'

services:
  keycloak:
    image: my-custom-keycloak:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-keycloak
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
